DIST:
    VERSION: hrnet-pretrain-one-more
    STORE_FREC: 1
    PRETRAIN_MODEL: /bigdata03/traffic4cast2020/processed_data/hrnet-w48-{city}.pth
DATASET:
    NAME: DatasetV12
    VALID_INDEX: /bigdata03/traffic4cast2020/processed_data/valid_index.npz
    TEST_INDEX: /bigdata03/traffic4cast2020/processed_data/test_index.npz
    INPUT_CHANNELS: 197
    DAYS: [-7, -3, -2, -1, 1, 2, 3, 7]
OPTIM:
    NAME: FusedLAMB
    BATCH_SIZE: 4
    INIT_LR: 1e-2
    USE_LR_SCHEDULER: false
    WARM_UP_EPOCH: 1.0
    MAX_EPOCH: 1
    USE_LR_SCHEDULER: true
LOG: 
    DIR: /bigdata03/traffic4cast2020/log
    STEP: 1
MODEL:
    HIDDEN_ACTIVATION: ELU
    MODEL_CONFIG_FILE: /bigdata03/traffic4cast2020/config/w48.yaml
    MODEL_VERSION: HighResolutionNetGeoEmbedding
    FROZEN_LAYERS: true