DIST:
    VERSION: hrnet-pretrain
    STORE_FREC: 5
    PRETRAIN_MODEL: ./traffic4cast2020/processed_data/hrnet_w48.pth
DATASET:
    NAME: PretrainDataset
    INPUT_CHANNELS: 45
    OUTPUT_CHANNELS: 18
    DATA_PATH: /home/omnisky/DATA2019
OPTIM:
    NAME: FusedLAMB
    BATCH_SIZE: 4
    INIT_LR: 1e-2
    WARM_UP_EPOCH: 1.0
    MAX_EPOCH: 15
    USE_LR_SCHEDULER: true
LOG: 
    DIR: ./traffic4cast2020/log
    STEP: 10
MODEL:
    HIDDEN_ACTIVATION: ELU
    MODEL_CONFIG_FILE: ./traffic4cast2020/config/w48.yaml
    MODEL_VERSION: HighResolutionNet