DIST:
    VERSION: v1-hernet-base-lr-001
    STORE_FREC: 5
    PRETRAIN_MODEL: /bigdata03/traffic4cast2020/processed_data/hrnet_w18_small_model_v2.pth
DATASET:
    NAME: BaseDataset
    VALID_INDEX: /bigdata03/traffic4cast2020/processed_data/valid_index.npz
    TEST_INDEX: /bigdata03/traffic4cast2020/processed_data/test_index.npz
OPTIM:
    NAME: FusedLAMB
    BATCH_SIZE: 8
    INIT_LR: 1e-2
    WARM_UP_EPOCH: 1.0
    MAX_EPOCH: 40
LOG: 
    DIR: /bigdata03/traffic4cast2020/log
    STEP: 1