DIST:
    VERSION: v3-hrnet-10-exponent-lr
    STORE_FREC: 5
    PRETRAIN_MODEL: ./traffic4cast2020/processed_data/hrnet_w18_small_model_v2.pth
DATASET:
    NAME: DatasetV7
    VALID_INDEX: ./traffic4cast2020/processed_data/valid_index.npz
    TEST_INDEX: ./traffic4cast2020/processed_data/test_index.npz
    INPUT_CHANNELS: 204
    DAYS: [-14, -7, -3, -2, -1, 1, 2, 3, 7, 14]
OPTIM:
    NAME: FusedLAMB
    BATCH_SIZE: 8
    INIT_LR: 1e-2
    WARM_UP_EPOCH: 1.0
    MAX_EPOCH: 20
    USE_LR_SCHEDULER: true
    LR_SCHEDULER_TYPE: get_exponent_schedule_with_warmup
    EXPONENT: 0.9985
LOG: 
    DIR: ./traffic4cast2020/log
    STEP: 10