DIST:
    VERSION: v4-hrnet-w48-include-valid
    STORE_FREC: 5
    PRETRAIN_MODEL: ./traffic4cast2020/weights/v4-hrnet-w48-include-valid-{city}-best.pth
DATASET:
    NAME: DatasetV11
    VALID_INDEX: ./traffic4cast2020/processed_data/valid_index.npz
    TEST_INDEX: ./traffic4cast2020/processed_data/test_index.npz
    INPUT_CHANNELS: 189
    DAYS: [-7, -3, -2, -1, 1, 2, 3, 7]
OPTIM:
    NAME: FusedLAMB
    BATCH_SIZE: 4
    INIT_LR: 5e-3
    WARM_UP_EPOCH: 0.0
    MAX_EPOCH: 5
    USE_LR_SCHEDULER: true
LOG: 
    DIR: ./traffic4cast2020/log
    STEP: 10
MODEL:
    HIDDEN_ACTIVATION: ELU
    MODEL_CONFIG_FILE: ./traffic4cast2020/config/w48.yaml