DIST:
    VERSION: v5-hrnet-base
    STORE_FREC: 5
    PRETRAIN_MODEL: ./traffic4cast2020/processed_data/hrnet_w18_small_model_v2.pth
DATASET:
    NAME: DatasetV10
    VALID_INDEX: ./traffic4cast2020/processed_data/valid_index.npz
    TEST_INDEX: ./traffic4cast2020/processed_data/test_index.npz
    INPUT_CHANNELS: 189
    DAYS: [-7, -3, -2, -1, 1, 2, 3, 7]
OPTIM:
    NAME: FusedLAMB
    BATCH_SIZE: 8
    INIT_LR: 1e-2
    WARM_UP_EPOCH: 1.0
    MAX_EPOCH: 15
    USE_LR_SCHEDULER: true
LOG: 
    DIR: ./traffic4cast2020/log
    STEP: 10
MODEL:
    HIDDEN_ACTIVATION: ELU
    MODEL_VERSION: HighResolutionNetGaussRank
    NAME: hrnet