DIST:
    VERSION: v6-hrnet-sun-fix-dst-include-valid
    STORE_FREC: 1
    PRETRAIN_MODEL: ./traffic4cast2020/weights/v6-hrnet-sun-fix-dst-include-valid-{city}-best.pth
DATASET:
    NAME: DatasetV19
    VALID_INDEX: ./traffic4cast2020/processed_data/valid_index.npz
    TEST_INDEX: ./traffic4cast2020/processed_data/test_index.npz
    INPUT_CHANNELS: 203
    DAYS: [-7, -3, -2, -1, 1, 2, 3, 7]
OPTIM:
    NAME: FusedLAMB
    BATCH_SIZE: 4
    INIT_LR: 5e-3
    WARM_UP_EPOCH: 0.0
    MAX_EPOCH: 5
    USE_LR_SCHEDULER: true
LOG: 
    DIR: ./traffic4cast2020/log
    STEP: 10
MODEL:
    HIDDEN_ACTIVATION: ELU
    MODEL_CONFIG_FILE: ./traffic4cast2020/config/w48.yaml
    MODEL_VERSION: HighResolutionNetGeoEmbedding